loki_controller:
  ros__parameters:

    max_pitch_cmd: 15.0   # (in deg, downward)
    alpha:          0.7    

    # ── Speed ────────────────────────────────────────────────────
    speed:
      kp:          10.0
      ki:          0.0
      kd:          0.0
      antiwindup:  0.0
      output_max:  400.0
      output_min: -400.0

    # ── Yaw ──────────────────────────────────────────────────────
    yaw:
      kp:          101.0
      ki:          0.0
      kd:          0.0
      antiwindup:  0.0
      output_max:  400.0
      output_min: -400.0

    # ── Depth outer loop ──────────────────────────────────────────
    depth:
      kp:          10.0
      ki:          0.0
      kd:          0.0
      antiwindup:  0.0
      output_max:  15.0
      output_min: -15.0

    # ── Pitch inner loop ──────────────────────────────────────────
    pitch:
      kp:          10.0
      ki:          0.0
      kd:          0.0
      antiwindup:  0.0
      output_max:  400.0
      output_min: -400.0
