loki_controller:
  ros__parameters:

    max_pitch_cmd: 60.0   # (in deg, downward)
    alpha:          0.7    

    # ── Speed ────────────────────────────────────────────────────
    speed:
      kp:         1200.0
      ki:          200.0
      kd:            0.0
      antiwindup:  400.0
      output_max:  400.0
      output_min: -400.0

    # ── Yaw ──────────────────────────────────────────────────────
    yaw:
      kp:        -20.0
      ki:          0.0
      kd:         -1.0
      antiwindup:  0.0
      output_max:  400.0
      output_min: -400.0

    # ── Depth outer loop ──────────────────────────────────────────
    depth:
      kp:          5.0
      ki:          0.2
      kd:          2.0
      antiwindup:  30.0
      output_max:  20.0
      output_min: -50.0

    # ── Pitch inner loop ──────────────────────────────────────────
    pitch:
      kp:         20.0
      ki:          1.0
      kd:          2.0
      antiwindup:  250.0
      output_max:  400.0
      output_min: -400.0
